### PR TITLE
Debian patches

### PR DESCRIPTION
**Pull request by barak**

### CODE REVIEW

**Comment by barak** [comment]
These tiny mods are, in any case, too insignificant and mechanical for copyright.

**Comment by awalther1** [comment]
Hi Barak,

thanks for the patches. 
I will take care of them, if this is OK 
for you. Then, there is no need to
sign the copyright form.

Best regards

Andrea

**Comment by barak** [comment]
Thanks Andrea, although I signed already anyway. It was more a general copyright comment.

**Comment by barak** [comment]
PS As a more abstract matter, in `configure.ac` I think you're "supposed" to use autoconf's own conditional and control structures, like `AS_IF()` and `AS_CASE()`, instead of diving down directly to sh stuff. The autoconf info page on `AS_IF` says: _This macro should be used instead of plain ‘if’ in code outside of an ‘AC_DEFUN’ macro, ..._

**Pull request merged**
